import {
  Award,
  BarChart3,
  BedDouble,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  ClipboardList,
  Cloud,
  Database,
  FileText,
  Gem,
  GraduationCap,
  Handshake,
  HardHat,
  Headphones,
  Home,
  KeyRound,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Package,
  PiggyBank,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  Store,
  Target,
  TrendingUp,
  UserCheck,
  Utensils,
  Wallet,
  Warehouse,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon registry.
 *
 * Data files name their icon as a string so they stay serialisable and
 * importable from server components. This is the one place strings become
 * components. A typo resolves to the fallback rather than crashing the page —
 * it will look wrong, which is the intended signal.
 */
const registry: Record<string, LucideIcon> = {
  Award,
  BarChart3,
  BedDouble,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  ClipboardList,
  Cloud,
  Database,
  FileText,
  Gem,
  GraduationCap,
  Handshake,
  HardHat,
  Headphones,
  Home,
  KeyRound,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Package,
  PiggyBank,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  Store,
  Target,
  TrendingUp,
  UserCheck,
  Utensils,
  Wallet,
  Warehouse,
  Workflow,
  Zap,
};

export function getIcon(name: string): LucideIcon {
  return registry[name] ?? Sparkles;
}
